apiVersion: batch/v1
kind: Job
metadata:
  name: REPLACE_WITH_JOB_NAME
  namespace: fastapi
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: REPLACE_WITH_IMAGE_URI
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fastapi-secret
                  key: DATABASE_URL
